### ISSUE TITLE
Strict notice: "non-static method WP_Feed_Cache::create() should not be called statically"

### ISSUE THREAD

**Issue by dgmstuart** [dxw/whippet-server#55]
I'm getting the following error - is this a whippet bug or a wordpress bug?

    Strict notice: call_user_func_array() expects parameter 1 to be a valid callback, non-static method WP_Feed_Cache::create() should not be called statically in /Users/dxwduncan/.cache/whippet/wordpresses/latest/wp-includes/SimplePie/Registry.php at line 215

**Comment by tomdxw** [comment]
WordPress: https://core.trac.wordpress.org/ticket/29204
